<a href="https://colab.research.google.com/github/cosraj/learning_keras_with_tensorflow/blob/main/tensforflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os

import tensorflow as tf

import cProfile

In [4]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
print("a = {}",a)
print("b = {}",b)

a = {} tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
b = {} tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [ ]:
c = tf.matmul(a,b)
print("c = {}",c)